# Site settings
title: Joachim Fainberg
email: joachimfainberg+web@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Joachim Fainberg is an AI/ML tech lead.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jfainberg.github.io" # the base hostname & protocol for your site
github_username:  jfainberg
linkedin_username: jfainberg

# Build settings
markdown: kramdown
include: ['_pages']
